name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Node.js native addon (windows-2019)
    runs-on: windows-2019
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings
          path: build/Release/WindowsShutdownHandler.node
          if-no-files-found: error
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: yarn
#      - name: Remove unnecessary bindings config file
#        run: rm binding.gyp
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Remove linux build
        run: rm -rf build
      - name: Move artifacts
        run: mkdir -p build/Release && cp artifacts/bindings/WindowsShutdownHandler.node build/Release/WindowsShutdownHandler.node
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}